import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../../globals.css'
import Header from '@/components/header'
import { signIn } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nexia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: {
    lang: string
  }
}>) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <form
          action={async () => {
            'use server'
            await signIn()
          }}
        >
          <button
            type="submit"
            className="text-sm font-semibold leading-6 text-gray-900"
          >
            Log in <span aria-hidden="true">&rarr;</span>
          </button>
        </form>
        <Header />
        {children}
      </body>
    </html>
  )
}
